import { build } from 'esbuild';
await build({
  entryPoints: ['src/lib/stash/app.js'],
  outfile: 'public/tools/stash/app.js',
  bundle: true, format: 'esm', minify: true, target: ['es2022'],
  legalComments: 'eof',
  banner: { js: '// Generated by npm run build:stash. Edit src/lib/stash/, not this bundle.' },
});

import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const shell = ['/tools/stash/', ...['app.js', 'style.css', 'copy.svg', 'upload-simple.svg', 'file.svg', 'icon-32.png', 'icon-180.png', 'icon-192.png', 'icon-512.png', 'manifest.webmanifest'].map(file => '/tools/stash/' + file)];
const hash = createHash('sha256');
for (const url of shell) hash.update(await readFile('public' + url + (url.endsWith('/') ? 'index.html' : '')));
const template = await readFile('src/lib/stash/sw-template.js', 'utf8');
hash.update(template);
await writeFile('public/tools/stash/sw.js', template.replace('__CACHE__', JSON.stringify('stash-shell-' + hash.digest('hex').slice(0, 12))).replace('__SHELL__', JSON.stringify(shell)));
